theme: jekyll-theme-hacker
title: Akhil Pinnani
description: AI Developer | Fullstack Engineer | Project Coordinator
linkedin_url: https://www.linkedin.com/in/akhil-pinnani/
email: akhilrvpinnani@gmail.com
github_url: https://github.com/akhil-p-git
